title: Bath Inter Faith Group
description: Connecting people of good faith in Bath
theme: minima

logo: /assets/images/bathifgtestlogo2purple.jpg

header_pages:
  - index.md
  - principles.md
  - events.md
  - join.md

