title: Bath Inter Faith Group
description: Connecting people of good faith in Bath
theme: minima

email: info@bathifg.org.uk

header_pages:
  - index.md
  - news.md
  - events.md
  - principles.md
  - about.md
  - join.md
